### ISSUE TITLE
Faulty anchor link

### ISSUE THREAD

**Issue by Mitchell3514** [chauff/cse1500-web-transcripts#312]
## What is the problem?
The h3 on line `1565` of the js lecture is assigned the id `final-notes-`, whilst the corresponding navbar section links to `final-notes`, therefore the link does not work.
I wanted to PR, but wasn't sure whether changing the h3 from `final notes ...` to 'final notes...` would work or to simply change the navbar link to `final-notes-`, so I made it an issue instead.

## Browser
Google Chrome
Version 88.0.4324.104 (Official Build) (64-bit)

## Operating system
Win10 64

**Comment by chauff** [comment]
Thanks. Fixed.
